import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
export function validateMobileConfig(config) {
  const allowed = ['defaultServerUrl', 'androidHttpOrigin'];
  if (!config || Object.keys(config).some(key => !allowed.includes(key)))
    throw new Error('mobile.config.json 只允许服务地址，禁止填写任何密钥');
  for (const key of allowed) if (typeof config[key] !== 'string') throw new Error(`请填写 ${key} 字符串，或留空`);
  for (const [key, value] of Object.entries(config)) {
    if (!value) continue;
    let url;
    try { url = new URL(value); } catch { throw new Error(`${key} 地址无效`); }
    if (url.origin !== value || url.username || url.password) throw new Error(`${key} 必须是完整 origin，无路径、尾斜线或凭据`);
    const parts = url.hostname.split('.').map(Number);
    const privateIp = parts.length === 4 && parts.every(n => Number.isInteger(n) && n >= 0 && n < 256) &&
      (parts[0] === 10 || (parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31) || (parts[0] === 192 && parts[1] === 168));
    if (key === 'androidHttpOrigin' && (url.protocol !== 'http:' || !privateIp)) throw new Error('安卓明文例外仅允许一个私有 IPv4 origin');
    if (key === 'defaultServerUrl' && url.protocol !== 'https:' && value !== config.androidHttpOrigin) throw new Error('默认地址必须使用 HTTPS 或明确配置的安卓局域网例外');
  }
  return config;
}
export function renderNetworkSecurity(config) {
  validateMobileConfig(config);
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/configure-mobile.mjs. Edit mobile.config.json instead. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors><certificates src="system" /></trust-anchors>
    </base-config>${config.androidHttpOrigin ? `
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">${new URL(config.androidHttpOrigin).hostname}</domain>
    </domain-config>` : ''}
</network-security-config>
`;
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const root = new URL('../', import.meta.url);
  const config = validateMobileConfig(JSON.parse(await readFile(new URL('mobile.config.json', root), 'utf8')));
  if (!process.argv.includes('--check')) await writeFile(new URL('android/app/src/main/res/xml/network_security_config.xml', root), renderNetworkSecurity(config));
  console.log('Mobile configuration validated; no secrets embedded.');
}
